[theme]

# Primary accent for interactive elements
primaryColor = '#005577'

# Background color for the main content area
backgroundColor = '#EEEEEE'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#bcbcbc'

# Color used for almost all text
textColor = '#2A2F36'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
font = "sans serif"